### ISSUE TITLE
Gitignore do not ignore the generated file listOfSections

### ISSUE THREAD

**Issue by herrBez** [Augugrumi/Thesis-Template#6]
**Description**
the file `.gitignore` do not ignore the generated file listOfSections.

It is questionable also if the pdf should be ignored or not. What do you think? @mzanella , @Polpetta 
**Other issues**

**Comment by Polpetta** [comment]
You need to add "Fixe" in front of the number of the issue if you want to automatically close the ticket.

Btw, the generated binaries must always be ignored in a repository. The only exceptions where PDFs are allowed is in `/res/img/` imho
